version: "3"

services: 
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=epress-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev2
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports: 
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=epress-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
